### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by Dan33185** [timusus/Shuttle#42]
Nothing is found when searching for artist, no matter how unique the name is. I have tried multiple names with no success.

**Comment by timusus** [comment]
@Dan33185 can you give some examples of what you're searching for? 

I've noticed a fairly major  issue where the search does not   factor in spaces in between words. So if you search for 'presets' you're not likely to find a match if you have 'the presets' on your device. Will fix.

**Comment by Dan33185** [comment]
Here's a video of an example:

https://youtu.be/ulJL_rx3ZGM

**Comment by icarapovic** [comment]
For search, I haven't looked how its implemented ATM, but I searched for "voodoo" to find a song that I just downloaded (Nick_Jonas_-_Voodoo_(Official_video)) from YT, no meta data in file, so just the file name, and it wasn't found. That should still be a hit, as its a property from MediaStore (DISPLAY_NAME I think...) and it was in the list of all songs and recently added list.

**Comment by timusus** [comment]
4b3da5d13f3858191922ef3338da4ec7391e4292

**Comment by timusus** [comment]
Resolved with 724bac7d51457603dc47db890055814d749ce05a

**Comment by Dan33185** [comment]
Hmm, this is still not working for me even with the latest beta.

**Comment by timusus** [comment]
@Dan33185 can you please elaborate?

Please provide an example of the search query as well as the song, artist & album name of the song you're expecting to show up.

**Comment by Dan33185** [comment]
Example 1: searching for "Bob Dylan" returns zero results
Example 2: searching for "Desolation Row" by Bob Dylan on the album Highway 61 Revisited returns zero results.

I've also noticed Shuttle runs normally before I use the search function, but after searching, it slows to a crawl until I force it to quit.

**Comment by timusus** [comment]
@Dan33185 I'm having trouble replicating the issue. However, from your youtube video I did notice that Shuttle is performing pretty slow in general, and the search is particularly bad. I'll look into that - I think perhaps I can cancel the previous search a little faster as you're typing.

Still I'm not sure why your songs aren't showing up.

For each of your two examples, can you please tell me what the artist, album and song names are for one of the tracks that you would expect to show up after this search? I'm trying to figure out if your songs have some missing tags, or something peculiar about them causing the search to fail.

**Comment by timusus** [comment]
Reopening to investigate whether we can improve the performance by cancelling existing searches more quickly.. or something.

**Comment by Dan33185** [comment]
Artist: Bob Dylan
Album: Highway 61 Revisited
Song Name: Desolation Row

Searching in other apps works fine, I'm only having the problem in Shuttle for some reason.

**Comment by geecko86** [comment]
@Dan33185 Can you provide more info on your setup? What is your device, your android version, xposed modules, ..? Is your phone performing slow in general?
Are your songs on an SD Card by any chance?

@timusus What struck me most when watching the video was that there doesn't seem to be a progressbar animation while it's loading the songs, leaving the user wondering whether the app is failing or still loading.

**Comment by Dan33185** [comment]
Galaxy S4, Android 4.4.4 (Stock, rooted).

Xposed modules:

> Amplify
> Greenify
> NoSageVolumeWarning
> Samsung KitKat SystemServer Crash Fix
> YouTube Ad Away
> YouTube Background Playback

Phone is performing as expected otherwise. Songs are on a SD card, yes. Search works as expected in other apps (Pulsar+, Phonograph)

**Comment by timusus** [comment]
@geecko86 the thing is, songs are stored in memory. A search shouldn't take more than 100ms or so. Usually I'd be all for showing a loader, but I think we'd be working around this bug instead of just finding the cause and fixing it. (Or maybe we should do both).

**Comment by timusus** [comment]
I wonder if this is related to #79. @Dan33185 does #79 apply to you at all?

**Comment by Dan33185** [comment]
It doesn't take minutes for my library to load, but usually at least 10-15 seconds, whereas other apps are usually instantaneous.

**Comment by timusus** [comment]
I'm convinced this is related to #79. If it's taking 15 seconds to load your songs, that's ridiculously slow - it's not surprising then that search results aren't showing up, since that requires acquiring and then filtering through your songs. 

Don't despair, I'm investigating #79 as a matter or priority.

**Comment by Dan33185** [comment]
Any update on this bug?

**Comment by timusus** [comment]
See comments in #79
