### ISSUE TITLE
Can't download missing artist and album images.

### ISSUE THREAD

**Issue by Clientsiman** [timusus/Shuttle#425]
**Shuttle version:**
 
v2.0.7 (Upgraded)
 
**Device, OS:**

 Nexus 5 , Android 6.0.1

**Description of bug:**

Can't download missing artist and album images. Old images that have been downloaded before with 2.06 are displaying normally. It's shows the downloading artwork bar after it finishes, no new images are shown. 
 
**Steps to reproduce:**
 
 1. Transfer a new album
 2. Settings-> Artwork-> Download Artwork->Download
 3. Wait to finish Downloading
 
**Expected outcome:**
 In v2.0.6 (Upgraded) I would have an image of the Artist 

**Observations/Actual Result:**
 On the Artist tab there are no images shown

**Comment by neekless** [comment]
Reproduced on pixel 2 xl shuttle+ v2.0.8.

Recently factory reset my phone, so shuttle+ is freshly installed. Notification of artwork download progress appears but after that no artwork is present (other than a few embedded artworks). The cache of the app is also tiny (<5mb) whereas before I factory reset the cache was close to 200mb, majority of that I assume is taken up by artwork.

**Comment by timusus** [comment]
Is this issue only occurring when using the 'download artwork' button? If you are on WiFi (or you have 'download via WiFi only' switched _off_, does artwork still download when you scroll through your lists of albums and artists?

**Comment by VPD01** [comment]
Same issue here. Smartphone is a Motorola Moto Z, Android 8.0.0.
Using Shuttle+ 2.0.8, bug was present in 2.0.7 as well.

I get no Artist Artwork, It no longer automatically downloads new or missing Artist Artwork.

If i go to the 'download all missing artwork' option, it will say downloading and it appears to finish in notification bar, However after checking app nothing has been downloaded.

If i try to manually change the artwork for an artist individually, it will flash up with a grey box with Last.FM in bottom right for a second, the it disappears and all i have is the empty white box saying choose artwork.

I've tried deleting artwork via the apps options, cleared cache/data, completely uninstalled and reinstalled app and still the same issue, i have 'download via WiFi only' switched off and the issue occurs whether i'm using Data or WiFi.

I assume it's effecting Album Art, as others have stated, but personally i use embedded album art and only download Artist Artwork, so cannot confirm that part.

**Comment by timusus** [comment]
@VPD01 does artwork download automatically as you scroll through the albums/artists list (on WiFi)?

**Comment by VPD01** [comment]
> @VPD01 does artwork download automatically as you scroll through the albums/artists list (on WiFi)?

Nope, neither on WiFi or Data.

**Comment by neekless** [comment]
Tried a few things:

1. 'Download artwork' button, auto-download OFF, wifi only ON, using wifi
2. 'Download artwork' button, auto-download OFF, wifi only OFF, using wifi and data
3. 'Download artwork' button, auto-download OFF, wifi only OFF, using wifi and data
4. Auto-download ON, wifi only ON, using wifi, scroll through songs/artists/albums
5. Auto-download ON, wifi only OFF, using wifi and data, scroll through songs/artists/albums

No artwork downloaded. I have 'prefer last.fm artwork' for albums turned on too, and they fail to download. Manually choosing artwork is also not working for artists, and manually choosing artwork works only for itunes artworks. Here is video for reference: https://drive.google.com/open?id=1XKoPSvw99amrb3YzMArG_g-CxcpkeB0I

Maybe there is some problem connecting to last.fm/itunes?

**Comment by timusus** [comment]
Thanks for the info. I'm not sure what's going on, as this is working for me in development.  I'm wondering if there's something wrong with the LastFM API key..

**Comment by VPD01** [comment]
Just to add, i use 'prefer last.fm artwork' option as well.
But disabling/trying to get artwork from itunes doesn't work for me either, it just shows up blank with no artist/album art.

However that has been the case for me for a while for me now, itunes art not working, but as i used last.fm i just kinda of forgot about it.

**Comment by timusus** [comment]
Thanks for the info. This is resolved and will be released shortly.

**Comment by neekless** [comment]
@timusus not resolved in 2.0.9 :/

**Comment by timusus** [comment]
@neekless that's very surprising.. Are you sure there isn't an issue with your settings / WiFi?

**Comment by neekless** [comment]
2.0.9 is also performing poorly. Choppy scrolling through lists and slow loading when opening the app and/or going back to the lists from shuttle settings. Could https://github.com/timusus/Shuttle/commit/bd9a8f251ab64a3793418e6a9f57a343625ec42e and https://github.com/timusus/Shuttle/commit/752e6f99aeec1b604e0ab3604e63030a84ce125e cause this?

**Comment by timusus** [comment]
Possibly the RxJava assembly tracing stuff. It probably should only be enabled for debug builds, but I really need some more info on some crashes.

**Comment by neekless** [comment]
Good new is the performance is back to what it was in 2.0.10 beta1, which doesn't have the tracking stuff if I am correct.

Bad news is artwork is still not downloading.

**Comment by timusus** [comment]
OK, so I have established that the Last.FM API is down. There was a bit of a red herring - I upgraded my macbook recently, and I also deployed the previous release from my machine (instead of the continuous deployment system), and I don't have the LastFM API key stored on this new machine. So the Last.FM API key was missing in 2.0.8 (I think).

But, none of this matters, as the Last.FM API isn't working regardless of the API key.

**Comment by neekless** [comment]
So I turned off 'Prefer Last.fm artwork' and my album artworks downloaded from iTunes. Is there a reason why this setting is only applied to album artwork only? Maybe artist images can have this setting too so that they can use itunes artwork.

Maybe I'm wrong about this, but does the 'Prefer Last.fm artwork' option make it download images from  only last.fm (and not download anything if it fails) or will it download from itunes if last.fm fails? I would think it's the latter but it seems that's not the case, as my album artworks only downloaded from itunes when I turned off this option.

**Comment by timusus** [comment]
iTunes don't host artist images IIRC.

For album images, Shuttle is supposed to fall back to iTunes if Last.FM fails. I think the LastFM request is timing out, so possibly because it takes too long, the entire image load is cancelled (including falling back to iTunes). This isn't ideal, but I'll have to investigate further.

**Comment by Clientsiman** [comment]
I can confirm that if I have 'Prefer Last.fm artwork' option no album images will be downloaded. If I remove the Prefer Last.fm artwork option iTunes will download the artwork. No artist image though. 

Performance is really bad in this 2.09 build. Everything is slower. It takes seconds from pressing an Artist util it shows all of the artist albums. Also entering and exiting the settings is very slow.

**Comment by timusus** [comment]
The Last.Fm API is down. I've implemented a fix which should ensure album artwork falls back to iTunes, but there's nothing I can do about artist artwork at the moment.

**Comment by neekless** [comment]
Looks like last.fm api is back up I got my artist artworks again!

**Comment by DaFlowah** [comment]
This is still an issue on mine.
OnePlus 5, stock ROM (with Magisk) on OxygenOS 9.0.4.
Shuttle+ 2.0.10.
Tried to cancel and download back artworks, but didn't solve the issue.

![photo_2019-05-04_12-53-40](https://user-images.githubusercontent.com/33235583/57178645-aa589980-6e6b-11e9-9c75-2910a32d8dd6.jpg)
