### ISSUE TITLE
Last.fm Album Artwork Not Downloading

### ISSUE THREAD

**Issue by cuancena** [timusus/Shuttle#462]
**Shuttle version:**
 
 v2.0.10
 
**Device, OS:**
 
Google Pixel 2 XL, Android 9 Pie (May 2019)

**Description of bug:**
 
Version 2.0.10, which seems to have been released to fix Last.fm artwork, actually caused this issue for me. I didn't have an issue before the update (I didn't try 2.0.9, so it may have been there). Album artwork refuses to download.

**Comment by naeemgul90** [comment]
Last.fm announced that they are not allowing developers to use any artist images from now on. However, I have fixed it somehow with something else.

**Comment by timusus** [comment]
Last.fm made unannounced, breaking changes to their API, preventing artwork from downloading. I'm working on a fix for this, which involves deploying my own artwork backend. This is a more robust fix than just using some other third party service, so it's taking a bit longer.

**Comment by timusus** [comment]
Fixed, will be published shortly

**Comment by Clientsiman** [comment]
I still have the problem with Artist not having an image using 2.0.11 upgraded in my Nexus 5 running Android 6.0.1

**Comment by timusus** [comment]
@Clientsiman perhaps an image can't be found for that particular artist? Can you name the artist you're having trouble with, as it appears in the app?

**Comment by Clientsiman** [comment]
To name a few : Behemoth , Deafheaven , KMFDM , Marduk, Mgla, Panopticon , Pro-Pain, Rammstein ,  Thy Catafalque,

**Comment by timusus** [comment]
@Clientsiman I've just checked these. KMFDM, Mgla and Pro-Pain are the only ones that couldn't be found. They may be obscure, incorrectly titles, or otherwise not known to Discogs.

**Comment by Clientsiman** [comment]
It's weird cos in Discogs site there are plenty of images for KMFDM , Mgla and Pro-Pain. The thing is that there is no image only in Artist , Album images are all good. Maybe I'll try reinstall the app later after work.  I tried the three dots-> choose artwork but still doesn't find any .
Thanks for you time anyway Tim. :-)

**Comment by timusus** [comment]
I'm still tweaking the server, so it might just be that it didn't find that artwork when you asked for it, and now it's stored as 'not found'. It's a work in progress, so expect artwork to be retrieved more reliably over the coming days.

**Comment by timusus** [comment]
@Clientsiman it should be finding those artists (and many others) now

**Comment by Clientsiman** [comment]
@timusus .
I have entered the beta to test if it's working there but no change.
All my artist have the a black image with the logo of the Shuttle, I tried the Delete Artwork  and then the Download Artwork. It says downloading images but that lasts 3-4 seconds and no art is downloaded. It has the same behavior as when the last.fm api was down few months ago. Normally it would need like a minute to download the art as I have many Artist.

If I press the tree dots then Choose artwork, it  first searches Media Store then Internet but doesn't find any Art. If I press biography it works for every Artist. The tags on the Artists are fine as Last FM never had any problem finding art, same it true for MusicBee in my PC.

Is there anything else I can try to find the problem as it seems it's working on everybody else?
Sorry for my bad English!
